// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FJFX_extract_minutiae_from_PGM
int FJFX_extract_minutiae_from_PGM(std::string inputfile, std::string outputfile);
RcppExport SEXP _fingermatchR_FJFX_extract_minutiae_from_PGM(SEXP inputfileSEXP, SEXP outputfileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type inputfile(inputfileSEXP);
    Rcpp::traits::input_parameter< std::string >::type outputfile(outputfileSEXP);
    rcpp_result_gen = Rcpp::wrap(FJFX_extract_minutiae_from_PGM(inputfile, outputfile));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fingermatchR_FJFX_extract_minutiae_from_PGM", (DL_FUNC) &_fingermatchR_FJFX_extract_minutiae_from_PGM, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fingermatchR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
