# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FJFX_extract_minutiae_from_PGM <- function(inputfile, outputfile) {
    .Call(`_fingermatchR_FJFX_extract_minutiae_from_PGM`, inputfile, outputfile)
}

